package Parsers;

public enum TokenType
{
    SELECT, FROM, ATTRIBUTE, OPERATOR, WHERE, COMMA, BRACKET_LEFT, BRACKET_RIGHT, EQUALS, LESS_THAN, GREATER_THAN,
    LESS_THAN_EQ, GREATER_THAN_EQ, NOT_EQUAL_TO, NUMBER

}



