package Parsers;

public enum TokenType
{

    COMMA, ASTERISK, EQUALS, SEMICOLON,
    BRACKET_LEFT, BRACKET_RIGHT,
    DOUBLE_EQUALS, LESS_THAN, GREATER_THAN, LESS_THAN_EQ, GREATER_THAN_EQ, NOT_EQUAL_TO, LIKE,
    FLOAT, INT, STRING,

    USE, CREATE, DROP, ADD, ALTER, INSERT, SELECT, UPDATE, DELETE, JOIN,
    DATABASE, TABLE,
    INTO, VALUES, FROM, SET, WHERE, ON,
    TRUE, FALSE,
    AND, OR,
    VARIABLE

}



